Repository tesler-platform/tesler-ui, pull requests merged in 2020-07, with the labels that each got.

#320 Add the ability to customize AssocListPopup on the client app
  src/components/Widget/Widget.tsx
  src/components/index.ts
  src/components/widgets/AssocListPopup/AssocListPopup.tsx
Labels: enhancement

#327 Layout fix to let customLayout be set
  src/components/View/View.tsx
Labels: bug

#332 Comments translation
  jest.config.js
  src/Provider.tsx
  src/actions/actions-utils.ts
  src/actions/actions.ts
  src/actions/index.ts
  src/api/api.ts
  src/api/index.ts
  src/components/Field/Field.tsx
  src/components/Multivalue/MultivalueField.test.tsx
  src/components/Widget/Widget.test.tsx
  src/components/ui/DatePickerField/DatePickerField.tsx
  src/components/widgets/FormWidget/FormWidget.test.tsx
  src/reducers/router.ts
  src/tests/assetsMock.ts
  src/utils/strings.ts
Labels: documentation

#331 Overriding epics from the client application (#330)
  src/Provider.tsx
  src/epics/data.ts
  src/epics/index.ts
  src/epics/router.ts
  src/epics/screen.ts
  src/epics/session.ts
  src/epics/view.ts
  src/imports/rxjs.ts
  src/interfaces/customEpics.ts
  src/utils/combineEpics.ts
Labels: enhancement

#340 `<AssocListPopup />` doesn't show already selected records in tags section; `saveAssociationsPassive` erroneously clears selected records (#339)
  src/components/widgets/AssocListPopup/AssocListPopup.tsx
  src/epics/data.ts
Labels: bug

#342 `<FullHierarchyComponent />` in 1.17.0 erroneously collapses the whole tree after selecting node (#341)
  src/components/FullHierarchyTable/FullHierarchyTable.tsx
Labels: bug

#344 User drilldown to the current cursor and `bcPath` shouldn't drop current cursor and fire drilldown respectively (#343)
  src/epics/router.ts
Labels: bug, invalid

#347 Refactor `<FullHierarchyComponent />` expanded rows routine to cover all cases of erroneous collapses of the whole tree after selecting node (#341)
  src/actions/actions.ts
  src/components/FullHierarchyTable/FullHierarchyTable.test.tsx
  src/components/FullHierarchyTable/FullHierarchyTable.tsx
  src/components/FullHierarchyTable/utils/hierarchySearchCache.test.ts
  src/components/FullHierarchyTable/utils/hierarchySearchCache.ts
  src/components/FullHierarchyTable/utils/useExpandedKeys.ts
  src/components/FullHierarchyTable/utils/useHierarchyCache.ts
  src/components/widgets/AssocListPopup/AssocListPopup.tsx
  src/hooks/useAssocRecords.ts
  src/interfaces/widget.ts
  src/reducers/view.ts
Labels: bug

#349 Hierarchy filter effect erroneously has reversed condition for early return (#341)
  src/components/FullHierarchyTable/utils/useExpandedKeys.ts
Labels: bug

#350 `showViewPopup` action should not initiate data fetch when popup BC is the same as in the initiator widget
  src/epics/data.ts
  src/reducers/screen.ts
Labels: bug

#355 Filter by date does not keep its state and erroneously shows time (#354)
  src/components/ColumnTitle/ColumnFilter.tsx
  src/components/ui/DatePickerField/DatePickerField.tsx
Labels: bug

#357 new `actionRole` property allowing custom operations to be be processed as a standard operation (#356)
  src/epics/data.ts
  src/epics/view.ts
  src/interfaces/operation.ts
  src/middlewares/preInvokeMiddleware.tsx
  src/middlewares/requiredFieldsMiddleware.ts
  src/utils/__tests__/operations.test.tsx
  src/utils/operations.ts
Labels: enhancement

#364 missing peer dependencies: `react`, `react-dom`, `redux`, `react-redux`, `moment`; move @types leftovers to devdependencies; update `webpack`, `react-dom`, `react-redux` (#336)
  package.json
  src/interfaces/widget.ts
  yarn.lock
Labels: dependencies

#365 Bump `typescript` from 3.8.3 to 3.9.7
  package.json
  src/middlewares/__tests__/autosaveMiddleware.test.ts
  src/middlewares/autosaveMiddleware.ts
  yarn.lock
Labels: dependencies

#366 Fixed checkout to branch from PR
  .github/workflows/build-alpha-from-pr.yml
Labels: bug

#361 Drildown with filters ability remove filter
  src/epics/router.ts
  src/reducers/screen.ts
Labels: bug, enhancement

#369 Incorrect check for `autoSaveBefore` in 1.18.0 causes required fields validation when it shouldn't (e.g. cancel operations) (#368)
  CHANGELOG.md
  src/middlewares/requiredFieldsMiddleware.ts
Labels: bug
