Repository tesler-platform/tesler-ui, pull requests merged in 2020-11, with the labels that each got.

#503 `<TreeVirtualized />` should not rely on input data being presorted: they might be not, which leads to children nodes expanding wrong direction
  src/components/ui/TreeVirtualized/TreeVirtualized.tsx
  src/components/ui/TreeVirtualized/__tests__/TreeVirtualized.test.tsx
  src/components/ui/TreeVirtualized/__tests__/TreeVirtualizedNode.test.tsx
  src/utils/__tests__/tree.test.ts
  src/utils/tree.ts
Labels: bug

#505 `bcNewDataEpic` should proccess postinvokes after dispatching `changeDataItem`, not before, otherwise pending changes might end up containing changes for BC that is no longer present
  src/actions/actions.ts
  src/epics/data.ts
  src/epics/data/__tests__/bcCancelCreateDataEpic.test.ts
  src/epics/data/__tests__/bcNewDataEpic.test.ts
  src/epics/data/bcNewDataEpic.ts
Labels: bug

#508 `icon` and `showOnlyIcon` are added to interface OperationGroup (#507)
  src/actions/actions.ts
  src/interfaces/operation.ts
  src/interfaces/view.ts
  src/reducers/view.ts
Labels: enhancement

#502 Hierarchy values shift
  src/components/FullHierarchyTable/FullHierarchyTable.less
  src/components/FullHierarchyTable/FullHierarchyTable.tsx
  src/interfaces/widget.ts
  src/utils/hierarchy.ts
Labels: enhancement

#509 export `drilldown` and `processPostInvoke` epics
  src/epics/router.ts
  src/epics/router/drilldown.ts
  src/epics/screen.ts
  src/epics/screen/processPostInvoke.ts
  src/index.ts
Labels: enhancement

#506 console helper `scrollToItem` for automation testing of `<TreeVirtualized />` components
  src/components/ui/TreeVirtualized/TreeVirtualized.tsx
  src/components/ui/TreeVirtualized/__tests__/TreeVirtualized.test.tsx
  src/utils/tree.ts
Labels: enhancement, tests

#511 1.24.0 erroneously missing `sendOperationEpicImpl` export
  src/epics/view.ts
  src/epics/view/sendOperation.ts
  src/index.ts
Labels: bug

#512 handling for http errors now can be customized through `apiError` (to override entire ajax onError handler) and `httpError` (to override handler only for specific http status code)
  src/actions/actions.ts
  src/epics/screen.ts
  src/epics/screen/__tests__/apiError.test.ts
  src/epics/screen/__tests__/httpError401.test.ts
  src/epics/screen/__tests__/httpError409.test.ts
  src/epics/screen/__tests__/httpError418.test.ts
  src/epics/screen/__tests__/httpError500.test.ts
  src/epics/screen/__tests__/httpErrorDefault.test.ts
  src/epics/screen/apiError.ts
  src/epics/screen/httpError401.ts
  src/epics/screen/httpError409.ts
  src/epics/screen/httpError418.ts
  src/epics/screen/httpError500.ts
  src/epics/screen/httpErrorDefault.ts
  src/index.ts
  src/utils/api.ts
Labels: enhancement

#517 missing http status epics export
  src/epics/screen.ts
Labels: bug

#518 use date picker component when searching by `dateTime` column
  src/components/ui/FilterField/FilterField.tsx
Labels: bug

#520 `saveAssociationsPassive` will crash on null values; export `<PickListField />`
  src/components/index.ts
  src/epics/data.ts
Labels: bug
