Repository tesler-platform/tesler-ui, pull requests merged in 2020-09, with the labels that each got.

#446 Bug of combination core and custom initial states is fixed (#445)
  src/Provider.tsx
Labels: bug

#429 Pagination component tests and refactoring
  src/components/ui/Pagination/Pagination.test.tsx
  src/components/ui/Pagination/Pagination.tsx
  src/components/widgets/PickListPopup/PickListPopup.test.tsx
Labels: documentation, tests

#430 filters utils tests; remove bo and dates utils
  src/components/ui/DatePickerField/DatePickerField.tsx
  src/epics/view.ts
  src/utils/__tests__/filters.test.ts
  src/utils/api.ts
  src/utils/bo.ts
  src/utils/dates.ts
  src/utils/filters.ts
Labels: tests
