Repository tesler-platform/tesler-ui, pull requests merged in 2020-06, with the labels that each got.

#250 AssocListPopup Tag style
  src/components/ui/Popup/Popup.less
  src/components/widgets/AssocListPopup/AssocListPopup.tsx
Labels: bug

#248 Data fetch should be initiated after successful save operation (#247)
  src/epics/data.ts
Labels: bug

#258 Autosave middleware reserved for tables erroneously applied to other widgets by `requiredFieldsMiddleware` (#257)
  src/index.ts
  src/interfaces/widget.ts
  src/middlewares/requiredFieldsMiddleware.ts
Labels: bug, enhancement

#227 initial current field values as pendingDataChanges when popup view
  src/epics/view.ts
Labels: bug

#262 Consideration of `limit` from widget metadata
  src/epics/data.ts
  src/interfaces/widget.ts
Labels: bug

#271 Table filtration and sorting not working due to missing prop dependency in columns hook (#270)
  src/components/widgets/TableWidget/TableWidget.tsx
Labels: bug

#273 bcName to API Query Parameters request
  src/epics/data.ts
Labels: enhancement

#279 AsscoListPopup Tag value field key
  src/epics/view.ts
Labels: bug

#275 The type `DataValue` extended by `DataItem[]` for cases if need to s…
  src/interfaces/data.ts
Labels: enhancement

#286 Deprecate `bcName` and unused properties for `<TableWidget />`; export missing components
  src/actions/actions.ts
  src/components/index.ts
  src/components/ui/Multivalue/MultivalueList.tsx
  src/components/widgets/TableWidget/TableWidget.tsx
  src/epics/view.ts
Labels: enhancement

#288 Replace data fetch request for save operiations with meta fetch and children bc data fetch, as the data of the source bc might be isolated during the draft stage and unavailable until the record is saved (#247)
  src/epics/data.ts
Labels: bug

#277 Select all checkbox in FullHierarchyTable
  src/components/FullHierarchyTable/FullHierarchyTable.tsx
Labels: enhancement

#293 PickListPopup remove footer buttons and fix title
  src/components/ui/Popup/Popup.tsx
  src/components/widgets/PickListPopup/PickListPopup.less
  src/components/widgets/PickListPopup/PickListPopup.tsx
Labels: enhancement

#311 Revert "rebuild speedup"
  package.json
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: bug
