Repository tesler-platform/tesler-ui, pull requests merged in 2020-08, with the labels that each got.

#373 Translate jsdoc for utilities, deprecate usage of `ObjectMap` type
  src/epics/view.ts
  src/interfaces/objectMap.ts
  src/interfaces/screen.ts
  src/reducers/screen.ts
  src/utils/api.ts
  src/utils/bo.ts
  src/utils/history.ts
  src/utils/redux.ts
Labels: documentation

#352 `<ColumnTitle />` refactoring and test coverage
  package.json
  src/components/ColumnTitle/ColumnFilter.less
  src/components/ColumnTitle/ColumnFilter.tsx
  src/components/ColumnTitle/ColumnSort.tsx
  src/components/ColumnTitle/ColumnTitle.tsx
  src/components/ColumnTitle/__tests__/ColumnFilter.test.tsx
  src/components/ColumnTitle/__tests__/ColumnSort.test.tsx
  src/components/ColumnTitle/__tests__/ColumnTitle.test.tsx
  src/components/FilterPopup/FilterPopup.less
  src/components/FilterPopup/FilterPopup.test.tsx
  src/components/FilterPopup/FilterPopup.tsx
  src/components/ui/CheckboxFilter/CheckboxFilter.less
  src/components/ui/CheckboxFilter/CheckboxFilter.test.tsx
  src/components/ui/CheckboxFilter/CheckboxFilter.tsx
  src/components/ui/FilterField/FilterField.test.tsx
  src/components/ui/FilterField/FilterField.tsx
  src/interfaces/view.ts
  src/utils/__tests__/filters.test.ts
  src/utils/filters.ts
  yarn.lock
Labels: tests

#397 <Dictionary/>: added `multiple` mode for several items selecting
  src/components/Field/Field.tsx
  src/components/ui/Dictionary/Dictionary.test.tsx
  src/components/ui/Dictionary/Dictionary.tsx
  src/interfaces/data.ts
  src/interfaces/widget.ts
Labels: enhancement

#372 MVG filter, dataItem keys.
  src/components/ColumnTitle/ColumnFilter.tsx
  src/components/widgets/AssocListPopup/AssocListPopup.tsx
Labels: bug

#412 Alpha build version comparison was fixed
  .github/workflows/build-alpha-from-pr.yml
Labels: bug, workflow

#394 AssocListPopup Tag
  src/components/widgets/AssocListPopup/AssocListPopup.tsx
Labels: bug

#422 Add ability to exclude widget from being wrapped in <Card /> (for alpha build)
  src/components/View/View.tsx
  src/components/Widget/Widget.test.tsx
  src/components/Widget/Widget.tsx
  src/components/ui/DashboardLayout/DashboardLayout.tsx
  src/interfaces/widget.ts
Labels: alpha

#404 FullHierarchy search enhancement
  src/components/FilterPopup/FilterPopup.tsx
  src/components/FullHierarchyTable/FullHierarchyTable.tsx
  src/components/FullHierarchyTable/utils/useExpandedKeys.ts
  src/components/FullHierarchyTable/utils/useHierarchyCache.ts
  src/epics/data.ts
  src/interfaces/widget.ts
Labels: bug, enhancement

#416 AssocListPopup Tag fix
  src/components/widgets/AssocListPopup/AssocListPopup.tsx
  src/hooks/useAssocRecords.ts
Labels: bug

#407 saveAssociations action postInvoke support
  src/epics/data.ts
Labels: enhancement

#395 Added `<InfoWidget/>` component
  src/components/Field/Field.tsx
  src/components/TemplatedTitle/TemplatedTitle.tsx
  src/components/Widget/Widget.test.tsx
  src/components/Widget/Widget.tsx
  src/components/widgets/InfoWidget/InfoWidget.tsx
  src/components/widgets/InfoWidget/__test__/InfoWidget.test.tsx
  src/components/widgets/InfoWidget/components/InfoCell.less
  src/components/widgets/InfoWidget/components/InfoCell.tsx
  src/components/widgets/InfoWidget/components/InfoRow.less
  src/components/widgets/InfoWidget/components/InfoRow.tsx
  src/components/widgets/InfoWidget/components/InfoValueWrapper.less
  src/components/widgets/InfoWidget/components/InfoValueWrapper.tsx
  src/components/widgets/InfoWidget/components/__tests__/InfoCell.test.tsx
  src/components/widgets/InfoWidget/components/__tests__/InfoRow.test.tsx
  src/components/widgets/InfoWidget/components/__tests__/InfoValueWrapper.test.tsx
  src/interfaces/widget.ts
Labels: enhancement
