Repository tesler-platform/tesler-ui, pull requests merged in 2020-10, with the labels that each got.

#463 Dictionary: Displaying of a placeholder is fixed (#462)
  src/components/ui/Dictionary/Dictionary.test.tsx
  src/components/ui/Dictionary/Dictionary.tsx
Labels: bug

#442 `pendingValidationFails` are divided by BC names and cursors (#441)
  src/components/Field/Field.tsx
  src/components/widgets/FormWidget/FormWidget.tsx
  src/epics/data.ts
  src/interfaces/view.ts
  src/middlewares/__tests__/requireFieldsMiddleware.ts
  src/middlewares/requiredFieldsMiddleware.ts
  src/reducers/view.ts
Labels: bug

#466 show notification when requested route references missing screen or view; notification can be customized by overriding `selectScreenFail` and `selectViewFail` epics of `router` slice
  src/assets/i18n/en.json
  src/assets/i18n/ru.json
  src/epics/router.ts
Labels: enhancement

#467 popup widgets are shown even when not invoked (#459)
  src/components/Widget/Widget.test.tsx
  src/components/Widget/Widget.tsx
  src/interfaces/widget.ts
Labels: bug

#469 widget option `multiple` to allow selecting multiple records on `<FlatTreePopup />` widgets
  src/components/ui/Popup/PopupFooter.less
  src/components/ui/Popup/PopupFooter.tsx
  src/components/ui/TreeVirtualized/TreeVirtualized.tsx
  src/components/ui/TreeVirtualized/TreeVirtualizedNode.less
  src/components/ui/TreeVirtualized/TreeVirtualizedNode.tsx
  src/components/ui/TreeVirtualized/__tests__/TreeVirtualized.test.tsx
  src/components/ui/TreeVirtualized/__tests__/TreeVirtualizedNode.test.tsx
  src/components/widgets/FlatTree/FlatTree.less
  src/components/widgets/FlatTree/FlatTree.tsx
  src/components/widgets/FlatTree/FlatTreePopup.tsx
  src/components/widgets/FlatTree/__tests__/FlatTreePopup.test.tsx
  src/components/widgets/FlatTree/useMultipleSelect.ts
  src/components/widgets/FlatTree/useSingleSelect.ts
  src/interfaces/tree.ts
  src/interfaces/widget.ts
Labels: enhancement

#471 `testEpic` utility for unit testing epics and example for `removeMultivalueTag` test
  src/epics/__tests__/data/removeMultivalueTag.test.ts
  src/epics/data.ts
  src/tests/testEpic.ts
Labels: tests

#472 `TreeVirtualizedNode` should toggle a node on row click; extract `fileUploadConfirm` epic
  src/components/ui/TreeVirtualized/TreeVirtualizedNode.tsx
  src/epics/view.ts
  src/epics/view/__tests__/fileUploadConfirm.test.ts
  src/epics/view/fileUploadConfirm.ts
Labels: bug, tests

#477 autosave fires for empty pendingData
  src/middlewares/autosaveMiddleware.ts
Labels: bug

#479 Version update 1.22.2; `<TreeVirtualized />` handles `matchCase` option incorrectly; missing export for `<SearchHighlight />` component
  CHANGELOG.md
  package.json
  src/components/index.ts
  src/components/ui/TreeVirtualized/TreeVirtualized.tsx
Labels: bug

#481 Remove Multivalue tag bugs
  src/epics/__tests__/data/removeMultivalueTag.test.ts
  src/epics/data/removeMultivalueTag.ts
  src/middlewares/requiredFieldsMiddleware.ts
  src/reducers/view.ts
Labels: bug

#488 `cancel-create` operation should dispatch `sendOperationSuccess`
  src/epics/data.ts
  src/epics/data/__tests__/bcCancelCreateDataEpic.test.ts
  src/epics/data/__tests__/removeMultivalueTag.test.ts
  src/epics/data/bcCancelCreateDataEpic.ts
Labels: bug

#493 `TreeVirtualized` and `TreeVirtualizedNode` crash for null values
  src/components/ui/TreeVirtualized/TreeVirtualized.tsx
  src/components/ui/TreeVirtualized/TreeVirtualizedNode.tsx
  src/components/ui/TreeVirtualized/__tests__/TreeVirtualized.test.tsx
Labels: bug

#496 Pagination `LoadMore` update BC request fix
  src/epics/data.ts
  src/epics/data/__tests__/bcFetchDataEpic.test.ts
Labels: bug

#498 `requiredFieldsMiddleware` shouldn't fire when called on BC without a cursor (#497)
  src/middlewares/__tests__/requireFieldsMiddleware.test.ts
  src/middlewares/__tests__/requiredFieldsMiddleware.test.ts
  src/middlewares/requiredFieldsMiddleware.ts
  src/utils/strings.ts
Labels: bug

#500 `preInvokeMiddleware` tests
  src/middlewares/__tests__/preInvokeMiddleware.test.ts
  src/middlewares/preInvokeMiddleware.tsx
Labels: tests
