Repository tesler-platform/tesler-ui, pull requests merged in 2021-04, with the labels that each got.

#628 clear filters by drilldown operation (#627)
  src/epics/router/__tests__/drilldown.test.ts
  src/epics/router/drilldown.ts
Labels: bug

#634 ModalInvoke: Customization of button labels is added (#633)
  src/components/ModalInvoke/ModalInvoke.test.tsx
  src/components/ModalInvoke/ModalInvoke.tsx
  src/interfaces/operation.ts
Labels: enhancement

#625 Extension point is added to PopupWidgetTypes
  src/Provider.tsx
  src/components/Widget/Widget.tsx
  src/epics/data/bcFetchData.ts
  src/epics/data/removeMultivalueTag.ts
  src/epics/data/selectView.ts
  src/hooks/index.ts
  src/interfaces/widget.ts
  src/utils/__tests__/extendPopupWidgetTypes.test.ts
  src/utils/extendPopupWidgetTypes.ts
Labels: discussion

#546 `bcFetchRowMetaRequest` test api call
  src/epics/data/__tests__/bcFetchRowMetaRequest.test.ts
  src/epics/data/bcFetchRowMetaRequest.ts
Labels: tests

#636 Need to add the ability to set background color for multivalueHover field type (#635)
  src/components/Field/Field.test.tsx
  src/components/FullHierarchyTable/FullHierarchyTable.tsx
  src/components/HierarchyTable/HierarchyTable.tsx
  src/components/SameBcHierarchyTable/SameBcHierarchyTable.tsx
  src/components/ui/Multivalue/MultivalueHover.less
  src/components/ui/Multivalue/MultivalueHover.tsx
  src/components/widgets/TableWidget/TableWidget.tsx
Labels: enhancement

#549 `bcSaveData` epic tests
  src/epics/data.ts
  src/epics/data/__tests__/bcSaveData.test.ts
  src/epics/data/bcSaveData.ts
  src/index.ts
Labels: tests
